# Right side peripheral configuration (trackball side)

# Split keyboard configuration
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

# PMW3610 badjeff driver
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
